#! /usr/bin/env python
import sys
import os
if __name__ == "__main__":
    my_path = os.path.abspath(os.path.dirname(__file__))
    sys.path = [my_path] + sys.path
    import ovstest.frame.testsuite
    ovstest.frame.testsuite.get_instance().run()
