#! /usr/bin/env python
import re
import os
from __builtin__ import True
from Carbon.Aliases import true
import diff_state_machine as diff_state

class ParseExecption(Exception):
    def __init__(self,msg):
        super(ParseExecption,self).__init__()
        self.message = msg
    def __str__(self):
        return self.message
        
class DiffParseReport(object):
    def __init__(self):
        self.line=-1
        self.isadd=Flase
        self.content=[]
    def add(self,linenum,line_content):
        pass
    def delete(self,linenum,line_content):
        pass
    def report(self):
        pass

class DiffAddLine(object):
    def __init__(self):
        pass
    def process(self):
        pass
    
class DiffMinusLine(object):
    def __init__(self):
        pass
    def process(self):
        pass
            
class DiffParse(object):
    def __init__(self):
        self.origin=None
        self.diff=None
        pass
    

class DiffHeader(object):
    def __init__(self,origin,head):
        self.origin=origin
        self.head=head

class DiffSection(object):
    def __init__(self,orign_line,orign_first,head_line,head_first):
        self.orign_line = orign_line
        self.orign_first = orign_first
        self.head_line = head_line
        self.head_first = head_first
        
                 
class CommentsCheck(object):
    def __init__(self,path):
        self.file=open(path,'r')
        self.lineno=0
        self.line=None
        
    def readline(self):
        if self.line is not None:
            line = self.line
            self.line = None
            return line
        else:
            self.lineno = self.lineno+1
            return self.file.readline()
        
    def peekreadline(self):
        self.lineno = self.lineno+1
        self.line = self.file.readline()
        return self.line
            

    def _file_line_update(self,line,starts_with,header):
        if line == "%s /dev/null\n" % starts_with:
            if starts_with == '---':
                header.origin = '/dev/null'
            else:
                header.head = '/dev/null'
        elif line == '%s %s\n' % (starts_with,header.origin) or line == '%s %s\n' % (starts_with,header.head):
            pass
        else:
            return False
        return True
    
    def is_file_line(self,line,starts_with,header):
        if "---" == starts_with or "+++" == starts_with:
            return self._file_line_update(line, starts_with, header)
        return False
    
    def parse_diff_header(self,line):
        pattern=re.compile('a/([^ ]+) b/(.*)\n$')
        if not line.startswith('diff --git'):
            print("line not startswitch 'diff -git'",line)
            return False
        
        match=pattern.search(line)
        if not match or len(match.groups()) != 2:
            print("error",match)
            return False
        
        header = DiffHeader("a/%s" % match.group(1),"b/%s" % match.group(2))
        #print("*****",header.origin,header.head)
        
        #skip 'new file mode' 
        line=self.readline()
        if line.startswith('new file'):
        	line=self.readline()

        #skip 'index ' line
        if not line.startswith('index '):
            print("error line not startwith 'index'")
            return False
        
        line=self.readline()
        if not self.is_file_line(line,'---',header):
            print("error,----",line)
            return False
        
        line=self.readline()
        if not self.is_file_line(line,'+++',header):
            print("error,+++",line)
            return False
        
        self.diff_header = header
        return True
    
    def is_comments_line(self,line):
        #skip first character
        line=line[1:]
        line=line.strip()
        if line.startswith('#') or line.startswith('//'):
           return True
        #if line.startswith('/*'):
        #    if line.find('*/') != -1:
        #        return True
        #search more line
        return False
    
    def is_block_comments_line(self,line,insert_lines):
        line=line[1:]
        line=line.strip()
        if line.startswith('/*'):
            if line.ends_with('*/'):
                return True,-1
            for i in range(len(insert_lines)):
                if insert_lines[i].find('*/') != -1:
                    return True,i
            return False,-1
        return False,-1
                    
    def is_insert_comments_line(self,line,insert_lines):
        dict={ idx:insert_lines[idx] for idx in range(len(insert_lines))}
        key=None
        for idx,insert_line in dict.items():
            #print('*****',line,insert_line)
            if insert_line[1:].startswith(line):
                #no inc 1 here
                comment_line=insert_line[len(line):]
                #print('*****',comment_line,"+++++",self.is_comments_line(comment_line))
                if self.is_comments_line(comment_line):
                    #print('*****',comment_line,idx,len(dict))
                    key=idx
                    break
        if key is not None:
            dict.pop(key)
        #print(key is not None,key,dict,dict.values())
        return key is not None,dict.values()
                
    def check_comments_line(self,insert_lines,delete_lines):
        if not insert_lines and not delete_lines:
            return
        
        if insert_lines and delete_lines:
            for line in delete_lines:
                result,insert_lines=self.is_insert_comments_line(line[1:].rstrip('\n'),insert_lines)
                if result:
                    continue
                print("Warning (%s) line+-- (%s)" % (self.diff_header.head,line.rstrip('\n')))
            for line in insert_lines:
                if not self.is_comments_line(line):
                    print("Warning (%s) line+-+ (%s)" % (self.diff_header.head,line.rstrip('\n')))
            
        elif insert_lines:
            for line in insert_lines:
                if not self.is_comments_line(line):
                    print("Warning (%s) line++  (%s)" % (self.diff_header.head,line.rstrip('\n')))
        else:
            for line in delete_lines:
                print("Warning (%s) line--  (%s)" % (self.diff_header.head,line.rstrip('\n')))
            pass
        
#     def _get_next_state(self,input,current_state):
#         """
# state machine / input: '+'   '-'   'O'
#         0               1     2     0
#         1               1     3     5
#         2               4     2     5
#         3               5     3     5
#         4               4     5     5 
#         5               E     E     E
#         """
#         next_state=[
#             #state 0
#             [1,2,0],
#             #state 1
#             [1,3,5],
#             #state 2
#             [4,2,5],
#             #state 3
#             [5,3,5],
#             #state 4
#             [4,5,5],
#             #state 5
#         ]
#         if input!='+' and input!='-' and input!='O':
#             raise Exception('input error "%s"' % input)
#         if current_state < 0 or current_state >= 5:
#             raise Exception("current state error '%d'" % current_state)
#         
#         if input=='+':
#             index=0
#         elif input=='-':
#             index=1
#         else:
#             index=2
#             
#         return next_state[current_state][input]
    
#     def process_current_state(self,current_state):
#         if current_state not in [0,1,2,3,4,5]:
#             raise Exception("state error '%d'" % current_state)
#         if current_state == 5:
#             pass
#         else:
#             pass
        
    def parse_diff_line(self,section):
        state_machine=diff_state.DiffStateMachine()
        insert_lines=[]
        delete_lines=[]
        state=0
        
        while True:
            line = self.peekreadline()
            if not line:
                break
            
            if line.startswith('@@ '):
                break
            
            if line.startswith('diff --git'):
                break
            
            if line.startswith('+'):
                state=state_machine.get_next_state('+', state)
                if state != diff_state.DiffStateMachine.LAST_STATE:
                    insert_lines.append(line)
                    continue
            elif line.startswith('-'):
                state=state_machine.get_next_state('-', state)
                if state != diff_state.DiffStateMachine.LAST_STATE:
                    delete_lines.append(line)
                    continue
            else:
                state=state_machine.get_next_state('O', state)
                if state != diff_state.DiffStateMachine.LAST_STATE:
                    #print('ignore',line)
                    continue
            
            #state == diff_state.DiffStateMachine.LAST_STATE
            self.check_comments_line(insert_lines,delete_lines)
            #state machine reset
            state = 0
            insert_lines=[]
            delete_lines=[]
        self.check_comments_line(insert_lines,delete_lines)
        return True
                    
    def parse_diff_section(self,line):
        patterns={4:re.compile('@@ \-([0-9]+),([0-9]+) \+([0-9]+),([0-9]+) @@'),3:re.compile('@@ \-([0-9]+),([0-9]+) \+([0-9]+) @@')}
        for key,p in patterns.items():
            match=p.search(line)
            if not match:
                continue
            else:
                if  key == 4:
                    section = DiffSection(match.group(1),match.group(2),match.group(3),match.group(4))
                else:
                    section = DiffSection(match.group(1),match.group(2),match.group(3),0)
        if not section:
            print("error",line,match,match.groups() if match else "",self.diff_header.origin,self.diff_header.head)
            return False
        self.diff_section = section
        return True
        
    def parse(self):
        while True:
            line=self.readline()
            if not line:
                break
            if line.startswith('diff --git'):
                if not self.parse_diff_header(line):
                    raise ParseExecption("parse diff header line fail:'%s'" % line)
            elif line.startswith('@@ ') :
                if not self.parse_diff_section(line):
                    raise ParseExecption("parse diff section line fail:'%s'" % line)
                else: 
                    self.parse_diff_line(line)
            else:
                raise ParseExecption('no excpet line at %d:"%s"' % (self.lineno,line))
            
        
if __name__ == "__main__":
    try:
        CommentsCheck('./test.diff').parse()
    except ParseExecption as e:
        print(e)
    

